language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install Pillow
  - pip install pytest
# command to run tests
script:
  - pytest -q ./tests/test_tmp.py
