language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
before_install:
  - pip install -U pytest

install:
  - pip install Pillow
  - pip install pytest-cov

# command to run tests
script:
  - pytest --cov=./
  - bash <(curl -s https://codecov.io/bash) -cF python
